name: CI

on:
  push:
    branches: [master, main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: cargo fmt (check)
        run: cargo fmt --all -- --check

      - name: cargo check
        run: cargo check --locked

      - name: cargo build
        run: cargo build --locked
